#include "translator.h"

translator::translator(QString lang)
{
    languageset = lang;
}

QString translator::translateit(QString original) {

    QString base = "Be verbose|";
            base = base + "Show filenames inside scanned archives|";
            base = base + "Enable libclamav's debug messages|";
            base = base + "Only output error messages|";
            base = base + "Write to stdout instead of stderr. Does not affect 'debug' messages.|";
            base = base + "Disable summary at end of scanning|";
            base = base + "Only print infected files|";
            base = base + "Skip printing OK files|";
            base = base + "Sound bell on virus detection|";
            base = base + "Do not remove temporary files|";
            base = base + "Generate JSON description of scanned file(s). JSON will be printed and also-|";
            base = base + "Only load official signatures|";
            base = base + "Scan subdirectories recursively|";
            base = base + "Continue scanning within file after finding a match|";
            base = base + "Scan files and directories on other filesystems|";
            base = base + "Remove infected files. Be careful!|";
            base = base + "Load unsigned bytecode|";
            base = base + "Detect Possibly Unwanted Applications|";
            base = base + "Detect structured data (SSN, Credit Card)|";
            base = base + "Scan mail files|";
            base = base + "Enable email signature-based phishing detection|";
            base = base + "Enable URL signature-based phishing detection|";
            base = base + "Heuristic alerts|";
            base = base + "Stop scanning as soon as a heuristic match is found|";
            base = base + "Normalize html, script, and text files. Use normalize=no for yara compatibility|";
            base = base + "Scan PE files|";
            base = base + "Scan ELF files|";
            base = base + "Scan OLE2 containers|";
            base = base + "Scan PDF files|";
            base = base + "Scan SWF files|";
            base = base + "Scan HTML files|";
            base = base + "Scan xml-based document files|";
            base = base + "Scan HWP3 files|";
            base = base + "Scan archive files (supported by libclamav)|";
            base = base + "Alert on broken executable files (PE & ELF)|";
            base = base + "Alert on broken graphics files (JPEG, TIFF, PNG, GIF)|";
            base = base + "Alert on encrypted archives and documents|";
            base = base + "Alert on encrypted archives|";
            base = base + "Alert on encrypted documents|";
            base = base + "Alert on OLE2 files containing VBA macros|";
            base = base + "Alert on files that exceed max file size, max scan size, or max recursion limit|";
            base = base + "Alert on emails containing SSL mismatches in URLs|";
            base = base + "Alert on emails containing cloaked URLs|";
            base = base + "Alert on raw DMG image files containing partition intersections|";
            base = base + "Disable authenticode certificate chain verification in PE files|";
            base = base + "Dump authenticode certificate chain in PE files|";
            base = base + "Disable caching and cache checks for hash sums of scanned files.|";
// new with version 1.4.2 of clamav
            base = base + "Create temporary files for nested file scans that would otherwise be in-memory only|";
            base = base + "Generate JSON metadata for the scanned file(s). For testing & development use ONLY.|";
            base = base + "Return with a nonzero error code if virus database outdated.|";
            base = base + "Scan OneNote files|";
            base = base + "Scan image (graphics) files|";
            base = base + "Detect files by calculating image (graphics) fuzzy hashes|";
            base = base + "Create temporary files for nested file scans that would otherwise be in-memory only";


// translations de_DE
    QString base_de_DE = "Sei mitteilsam|";
            base_de_DE = base_de_DE + "Dateien innerhalb von Archiven anzeigen|";
            base_de_DE = base_de_DE + "Aktiviere libclamav's Debug Meldungen|";
            base_de_DE = base_de_DE + "Nur Fehlermeldungen ausgeben|";
            base_de_DE = base_de_DE + "Schreibe nach stdout anstatt nach stderr. Betrifft nicht 'debug' Meldungen.|";
            base_de_DE = base_de_DE + "Deaktiviere die Scanzusammenfassung am Ende des Scanvorgangs|";
            base_de_DE = base_de_DE + "Nur infizierte Dateien ausgeben|";
            base_de_DE = base_de_DE + "Überspringe die Ausgabe von OK Dateien|";
            base_de_DE = base_de_DE + "Klingel bei Viruserkennung|";
            base_de_DE = base_de_DE + "Temporäre Dateien nicht entfernen|";
            base_de_DE = base_de_DE + "Erstelle JSON Beschreibung von gescannten Dateien. JSON wird ausgegeben und auch-|";
            base_de_DE = base_de_DE + "Nur offizielle Signaturen laden|";
            base_de_DE = base_de_DE + "Scanne Unterverzeichnisse rekursiv|";
            base_de_DE = base_de_DE + "Fahre mit dem Scannen in der Datei fort wenn ein Treffer erziehlt wurde|";
            base_de_DE = base_de_DE + "Scanne Dateien und Verzeichnisse auf anderen Dateisystemen|";
            base_de_DE = base_de_DE + "Infizierte Dateien entfernen. Seien Sie vorsichtig!|";
            base_de_DE = base_de_DE + "Lade unsegnierten Bytecode|";
            base_de_DE = base_de_DE + "Erkenne vermutlich ungewollte Anwendungen|";
            base_de_DE = base_de_DE + "Erkenne strukturierte Daten (SSN, Credit Card)|";
            base_de_DE = base_de_DE + "Scanne Mail Dateien|";
            base_de_DE = base_de_DE + "Aktivieren Sie die Phishing-Erkennung mit E-Mail-Signaturen|";
            base_de_DE = base_de_DE + "Aktivieren der URL-Signatur und Phishing-Erkennung|";
            base_de_DE = base_de_DE + "Heuristische Warnungen|";
            base_de_DE = base_de_DE + "Beenden Sie die Suche, sobald eine heuristische Übereinstimmung gefunden wird.|";
            base_de_DE = base_de_DE + "Normalisieren Sie HTML-, Skript- und Textdateien. Verwenden Sie normalize=no für Yara-Kompatibilität|";
            base_de_DE = base_de_DE + "PE-Dateien scannen|";
            base_de_DE = base_de_DE + "ELF-Dateien scannen|";
            base_de_DE = base_de_DE + "OLE2-Container scannen|";
            base_de_DE = base_de_DE + "PDF-Dateien scannen|";
            base_de_DE = base_de_DE + "SWF-Dateien scannen|";
            base_de_DE = base_de_DE + "HTML-Dateien scannen|";
            base_de_DE = base_de_DE + "xml-basierte Dokumentdateien scannen|";
            base_de_DE = base_de_DE + "HWP3-Dateien scannen|";
            base_de_DE = base_de_DE + "Scannen von Archivdateien (unterstützt von libclamav)|";
            base_de_DE = base_de_DE + "Warnung vor defekten ausführbaren Dateien (PE & ELF)|";
            base_de_DE = base_de_DE + "Warnung bei defekten Grafikdateien (JPEG, TIFF, PNG, GIF)|";
            base_de_DE = base_de_DE + "Warnung vor verschlüsselten Archiven und Dokumenten|";
            base_de_DE = base_de_DE + "Warnung bei verschlüsselten Archiven|";
            base_de_DE = base_de_DE + "Warnung bei verschlüsselten Dokumenten|";
            base_de_DE = base_de_DE + "Warnung vor OLE2-Dateien, die VBA-Makros enthalten|";
            base_de_DE = base_de_DE + "Warnung bei Dateien, die die maximale Dateigröße, die maximale Scangröße oder die maximale Rekursionsgrenze überschreiten|";
            base_de_DE = base_de_DE + "Warnung bei E-Mails, die SSL-Fehlanpassungen in URLs enthalten|";
            base_de_DE = base_de_DE + "Warnung bei E-Mails mit getarnten URLs|";
            base_de_DE = base_de_DE + "Warnung bei rohen DMG-Image-Dateien, die Partitionsüberschneidungen enthalten|";
            base_de_DE = base_de_DE + "Deaktivieren der Authenticode-Zertifikatskettenprüfung in PE-Dateien|";
            base_de_DE = base_de_DE + "Dump der Authenticode-Zertifikatskette in PE-Dateien|";
            base_de_DE = base_de_DE + "Deaktivieren Sie die Zwischenspeicherung und die Cache-Prüfungen für Hash-Summen von gescannten Dateien.|";
// New with version 1.4.2 of clamav
            base_de_DE = base_de_DE + "Erstellen von temporären Dateien für verschachtelte Dateiscans, die sonst nur im Arbeitsspeicher gespeichert würden|";
            base_de_DE = base_de_DE + "Generieren Sie JSON-Metadaten für die gescannte(n) Datei(en). NUR für Test- und Entwicklungszwecke.|";
            base_de_DE = base_de_DE + "Gibt einen Fehlercode ungleich Null zurück, wenn die Virendatenbank veraltet ist.|";
            base_de_DE = base_de_DE + "OneNote-Dateien scannen|";
            base_de_DE = base_de_DE + "Scannen von Bilddateien (Grafiken)|";
            base_de_DE = base_de_DE + "Dateien durch Berechnung von Fuzzy-Hashes für Bilder (Grafiken) erkennen|";
            base_de_DE = base_de_DE + "Erstellen von temporären Dateien für verschachtelte Dateiscans, die sonst nur im Arbeitsspeicher gespeichert würden";


// translations pt_PT and all countries with portugese language
    QString base_pt_PT = "Ser detalhista|";
            base_pt_PT = base_pt_PT + "Mostrar nomes de ficheiros nos arquivos digitalizados|";
            base_pt_PT = base_pt_PT + "Ativar as mensagens de depuração da libclamav|";
            base_pt_PT = base_pt_PT + "Apenas mensagens de erro|";
            base_pt_PT = base_pt_PT + "Escreve para stdout em vez de stderr. Não afecta as mensagens de 'debug'.|";
            base_pt_PT = base_pt_PT + "Desativar o resumo no final da verificação|";
            base_pt_PT = base_pt_PT + "Imprimir apenas ficheiros infectados|";
            base_pt_PT = base_pt_PT + "Saltar a impressão de ficheiros OK|";
            base_pt_PT = base_pt_PT + "Sinal sonoro na deteção de vírus|";
            base_pt_PT = base_pt_PT + "Não remover ficheiros temporários|";
            base_pt_PT = base_pt_PT + "Gera uma descrição JSON do(s) ficheiro(s) digitalizado(s). O JSON será impresso e também...|";
            base_pt_PT = base_pt_PT + "Carregar apenas assinaturas oficiais|";
            base_pt_PT = base_pt_PT + "Pesquisar subdirectórios recursivamente|";
            base_pt_PT = base_pt_PT + "Continuar a procurar no ficheiro depois de encontrar uma correspondência|";
            base_pt_PT = base_pt_PT + "Analisar ficheiros e diretórios noutros sistemas de ficheiros|";
            base_pt_PT = base_pt_PT + "Remover ficheiros infectados. Cuidado!|";
            base_pt_PT = base_pt_PT + "Carregar bytecode sem assinatura|";
            base_pt_PT = base_pt_PT + "Detetar aplicações possivelmente indesejadas|";
            base_pt_PT = base_pt_PT + "Detetar dados estruturados (SSN, cartão de crédito)|";
            base_pt_PT = base_pt_PT + "Digitalizar ficheiros de correio|";
            base_pt_PT = base_pt_PT + "Ativar a deteção de phishing baseada em assinaturas de correio eletrónico|";
            base_pt_PT = base_pt_PT + "Ativar a deteção de phishing baseada em assinaturas de URL|";
            base_pt_PT = base_pt_PT + "Alertas heurísticos|";
            base_pt_PT = base_pt_PT + "Parar a pesquisa assim que for encontrada uma correspondência heurística|";
            base_pt_PT = base_pt_PT + "Normaliza ficheiros html, script e texto. Use normalize=no para compatibilidade com yara|";
            base_pt_PT = base_pt_PT + "Analisar ficheiros PE|";
            base_pt_PT = base_pt_PT + "Analisar ficheiros ELF|";
            base_pt_PT = base_pt_PT + "Verificar contentores OLE2|";
            base_pt_PT = base_pt_PT + "Analisar ficheiros PDF|";
            base_pt_PT = base_pt_PT + "Analisar ficheiros SWF|";
            base_pt_PT = base_pt_PT + "Analisar ficheiros HTML|";
            base_pt_PT = base_pt_PT + "Digitalizar ficheiros de documentos baseados em xml|";
            base_pt_PT = base_pt_PT + "Analisar ficheiros HWP3|";
            base_pt_PT = base_pt_PT + "Analisar ficheiros de arquivo (suportado pela libclamav)|";
            base_pt_PT = base_pt_PT + "Alerta sobre ficheiros executáveis danificados (PE & ELF)|";
            base_pt_PT = base_pt_PT + "Alerta sobre ficheiros gráficos danificados (JPEG, TIFF, PNG, GIF)|";
            base_pt_PT = base_pt_PT + "Alerta sobre arquivos e documentos encriptados|";
            base_pt_PT = base_pt_PT + "Alerta sobre arquivos encriptados|";
            base_pt_PT = base_pt_PT + "Alerta sobre documentos encriptados|";
            base_pt_PT = base_pt_PT + "Alerta sobre ficheiros OLE2 que contêm macros VBA|";
            base_pt_PT = base_pt_PT + "Alerta sobre ficheiros que excedem o tamanho máximo do ficheiro, o tamanho máximo da pesquisa ou o limite máximo de recursão|";
            base_pt_PT = base_pt_PT + "Alerta sobre mensagens de correio eletrónico com incompatibilidades SSL nos URLs|";
            base_pt_PT = base_pt_PT + "Alerta sobre mensagens de correio eletrónico que contenham URLs camuflados|";
            base_pt_PT = base_pt_PT + "Alerta sobre ficheiros de imagem DMG em bruto que contêm intersecções de partições|";
            base_pt_PT = base_pt_PT + "Desativar a verificação da cadeia de certificados authenticode nos ficheiros PE|";
            base_pt_PT = base_pt_PT + "Despejar a cadeia de certificados authenticode nos ficheiros PE|";
            base_pt_PT = base_pt_PT + "Desativar o armazenamento em cache e as verificações de cache para somas de hash de ficheiros digitalizados.|";
// new with version 1.4.2 of clamav
            base_pt_PT = base_pt_PT + "Criar ficheiros temporários para análises de ficheiros aninhados que, de outra forma, seriam apenas na memória|";
            base_pt_PT = base_pt_PT + "Gerar metadados JSON para o(s) ficheiro(s) digitalizado(s). APENAS para utilização em testes e desenvolvimento.|";
            base_pt_PT = base_pt_PT + "Retorna com um código de erro diferente de zero se a base de dados de vírus estiver desactualizada.|";
            base_pt_PT = base_pt_PT + "Digitalizar ficheiros OneNote|";
            base_pt_PT = base_pt_PT + "Digitalizar ficheiros de imagem (gráficos)|";
            base_pt_PT = base_pt_PT + "Detetar ficheiros através do cálculo de hashes difusos de imagens (gráficos)|";
            base_pt_PT = base_pt_PT + "Criar ficheiros temporários para análises de ficheiros aninhados que, de outra forma, seriam apenas na memória";

//  translation it_IT
    QString base_it_IT = "Essere prolissi|";
            base_it_IT = base_it_IT + "Mostra i nomi dei file all'interno degli archivi scansionati|";
            base_it_IT = base_it_IT + "Abilitare i messaggi di debug di libclamav|";
            base_it_IT = base_it_IT + "Emette solo messaggi di errore|";
            base_it_IT = base_it_IT + "Scrive su stdout invece che su stderr. Non influisce sui messaggi di debug.|";
            base_it_IT = base_it_IT + "Disabilita il riepilogo al termine della scansion|";
            base_it_IT = base_it_IT + "Stampa solo i file infetti|";
            base_it_IT = base_it_IT + "Salta la stampa dei file OK|";
            base_it_IT = base_it_IT + "Campanello sonoro per il rilevamento dei virus|";
            base_it_IT = base_it_IT + "Non rimuovere i file temporanei|";
            base_it_IT = base_it_IT + "Genera una descrizione JSON dei file scansionati. JSON verrà stampato e anche|";
            base_it_IT = base_it_IT + "Caricare solo le firme ufficiali|";
            base_it_IT = base_it_IT + "Scansione ricorsiva delle sottodirectory|";
            base_it_IT = base_it_IT + "Continuare la scansione all'interno del file dopo aver trovato una corrispondenza|";
            base_it_IT = base_it_IT + "Scansione di file e directory su altri filesystem|";
            base_it_IT = base_it_IT + "Rimuovere i file infetti. Attenzione!|";
            base_it_IT = base_it_IT + "Caricare il bytecode senza segno|";
            base_it_IT = base_it_IT + "Rilevare le applicazioni potenzialmente indesiderate|";
            base_it_IT = base_it_IT + "Rilevare dati strutturati (SSN, carta di credito)|";
            base_it_IT = base_it_IT + "Scansione di file di posta elettronica|";
            base_it_IT = base_it_IT + "Abilitare il rilevamento del phishing basato sulle firme delle e-mail|";
            base_it_IT = base_it_IT + "Abilitare il rilevamento del phishing basato sulle firme degli URL|";
            base_it_IT = base_it_IT + "Avvisi euristici|";
            base_it_IT = base_it_IT + "Interrompere la scansione non appena viene trovata una corrispondenza euristica.|";
            base_it_IT = base_it_IT + "Normalizza i file html, di script e di testo. Usare normalize=no per la compatibilità con yara|";
            base_it_IT = base_it_IT + "Scansione dei file PE|";
            base_it_IT = base_it_IT + "Scansione dei file ELF|";
            base_it_IT = base_it_IT + "Scansione dei contenitori OLE2|";
            base_it_IT = base_it_IT + "Scansione di file PDF|";
            base_it_IT = base_it_IT + "Scansione di file SWF|";
            base_it_IT = base_it_IT + "Scansione dei file HTML|";
            base_it_IT = base_it_IT + "Scansione di file di documenti basati su xml|";
            base_it_IT = base_it_IT + "Scansione dei file HWP3|";
            base_it_IT = base_it_IT + "Scansione di file di archivio (supportata da libclamav)|";
            base_it_IT = base_it_IT + "Avviso sui file eseguibili non funzionanti (PE e ELF)|";
            base_it_IT = base_it_IT + "Avviso su file grafici non funzionanti (JPEG, TIFF, PNG, GIF)|";
            base_it_IT = base_it_IT + "Allarme su archivi e documenti criptati|";
            base_it_IT = base_it_IT + "Avviso su archivi criptati|";
            base_it_IT = base_it_IT + "Allarme sui documenti criptati|";
            base_it_IT = base_it_IT + "Avviso su file OLE2 contenenti macro VBA|";
            base_it_IT = base_it_IT + "Avviso sui file che superano la dimensione massima del file, la dimensione massima della scansione o il limite massimo di ricorsione.|";
            base_it_IT = base_it_IT + "Avviso su e-mail contenenti errori di corrispondenza SSL negli URL|";
            base_it_IT = base_it_IT + "Allarme sulle e-mail contenenti URL occultati|";
            base_it_IT = base_it_IT + "Avviso su file immagine DMG grezzi contenenti intersezioni di partizioni|";
            base_it_IT = base_it_IT + "Disabilitare la verifica della catena di certificati authenticode nei file PE|";
            base_it_IT = base_it_IT + "Eseguire il dump della catena di certificati authenticode nei file PE|";
            base_it_IT = base_it_IT + "Disattivare la cache e i controlli della cache per le somme hash dei file scansionati.|";
// New with version 1.4.2 of clamav
            base_it_IT = base_it_IT + "Creazione di file temporanei per le scansioni di file annidati che altrimenti verrebbero memorizzati solo nella memoria di lavoro.|";
            base_it_IT = base_it_IT + "Genera metadati JSON per i file scansionati. Solo per scopi di test e sviluppo.|";
            base_it_IT = base_it_IT + "Restituisce un codice di errore non nullo se il database dei virus non è aggiornato.|";
            base_it_IT = base_it_IT + "Scansione di file OneNote|";
            base_it_IT = base_it_IT + "Scansione di file immagine (grafica)|";
            base_it_IT = base_it_IT + "Riconoscere i file calcolando hash fuzzy per le immagini (grafica)|";
            base_it_IT = base_it_IT + "Crea file temporanei per le scansioni di file annidati che altrimenti sarebbero solo in memoria.";

// translations da_DK
    QString base_da_DK = "Sei mitteilsam|";
            base_da_DK = base_da_DK + "Vis filer i arkiver|";
            base_da_DK = base_da_DK + "Aktiver libclamavs fejlfindingsmeddelelser|";
            base_da_DK = base_da_DK + "Udsender kun fejlmeddelelser|";
            base_da_DK = base_da_DK + "Skriv til stdout i stedet for stderr. Påvirker ikke 'debug'-meddelelser.|";
            base_da_DK = base_da_DK + "Deaktiver scanningsoversigten ved afslutningen af scanningsprocessen|";
            base_da_DK = base_da_DK + "Udsender kun inficerede filer|";
            base_da_DK = base_da_DK + "Spring output af OK-filer over|";
            base_da_DK = base_da_DK + "Klokke til virusdetektion|";
            base_da_DK = base_da_DK + "Fjern ikke midlertidige filer|";
            base_da_DK = base_da_DK + "Opret JSON-beskrivelse af scannede filer. JSON er output og også|";
            base_da_DK = base_da_DK + "Indlæs kun officielle underskrifter|";
            base_da_DK = base_da_DK + "Scan undermapper rekursivt|";
            base_da_DK = base_da_DK + "Fortsæt med at scanne i filen, hvis der opnås et hit|";
            base_da_DK = base_da_DK + "Scan filer og mapper på andre filsystemer|";
            base_da_DK = base_da_DK + "Fjern inficerede filer. Vær forsigtig!|";
            base_da_DK = base_da_DK + "Indlæs usegmenteret bytekode|";
            base_da_DK = base_da_DK + "Genkender formentlig uønskede programmer|";
            base_da_DK = base_da_DK + "Genkender strukturerede data (SSN, kreditkort)|";
            base_da_DK = base_da_DK + "Scanning af mailfiler|";
            base_da_DK = base_da_DK + "Aktivér phishing-registrering med e-mail-signaturer|";
            base_da_DK = base_da_DK + "Aktivér URL-signatur og phishing-registrering|";
            base_da_DK = base_da_DK + "Heuristiske advarsler|";
            base_da_DK = base_da_DK + "Stop søgningen, så snart der er fundet et heuristisk match.|";
            base_da_DK = base_da_DK + "Normaliser HTML-, script- og tekstfiler. Brug normalise=no for Yara-kompatibilitet|";
            base_da_DK = base_da_DK + "Scan PE-filer|";
            base_da_DK = base_da_DK + "Scanning af ELF-filer|";
            base_da_DK = base_da_DK + "Scan OLE2-container|";
            base_da_DK = base_da_DK + "Scan PDF-filer|";
            base_da_DK = base_da_DK + "Scan SWF-filer|";
            base_da_DK = base_da_DK + "Scan HTML-filer|";
            base_da_DK = base_da_DK + "Scan xml-baserede dokumentfiler|";
            base_da_DK = base_da_DK + "Scan HWP3-filer|";
            base_da_DK = base_da_DK + "Scanning af arkivfiler (understøttes af libclamav)|";
            base_da_DK = base_da_DK + "Advarsel om defekte eksekverbare filer (PE & ELF)|";
            base_da_DK = base_da_DK + "Advarsel om defekte grafikfiler (JPEG, TIFF, PNG, GIF)|";
            base_da_DK = base_da_DK + "Advarsel om krypterede arkiver og dokumenter|";
            base_da_DK = base_da_DK + "Advarsel for krypterede arkiver|";
            base_da_DK = base_da_DK + "Advarsel for krypterede dokumenter|";
            base_da_DK = base_da_DK + "Advarsel om OLE2-filer, der indeholder VBA-makroer|";
            base_da_DK = base_da_DK + "Advarsel for filer, der overskrider den maksimale filstørrelse, den maksimale scanningsstørrelse eller den maksimale rekursionsgrænse|";
            base_da_DK = base_da_DK + "Advarsel for e-mails, der indeholder SSL-misforhold i URL'er|";
            base_da_DK = base_da_DK + "Advarsel om e-mails med skjulte URL'er|";
            base_da_DK = base_da_DK + "Advarsel for rå DMG-billedfiler, der indeholder partitionsoverlapninger|";
            base_da_DK = base_da_DK + "Deaktivering af Authenticode-certifikatkædekontrol i PE-filer|";
            base_da_DK = base_da_DK + "Dump af Authenticode-certifikatkæden i PE-filer|";
            base_da_DK = base_da_DK + "Deaktiver caching og cache-kontrol af hashsummer for scannede filer.|";
// new with version 1.4.2 of clamav
            base_da_DK = base_da_DK + "Opret midlertidige filer til indlejrede filscanninger, der ellers kun ville være i hukommelsen|";
            base_da_DK = base_da_DK + "Generer JSON-metadata for de scannede filer. KUN til test- og udviklingsbrug.|";
            base_da_DK = base_da_DK + "Returneres med en fejlkode forskellig fra nul, hvis virusdatabasen er forældet.|";
            base_da_DK = base_da_DK + "Scan OneNote-filer|";
            base_da_DK = base_da_DK + "Scanning af billedfiler (grafik)|";
            base_da_DK = base_da_DK + "Registrer filer ved at beregne fuzzy hashes for billeder (grafik)|";
            base_da_DK = base_da_DK + "Opret midlertidige filer til indlejrede filscanninger, der ellers kun ville være i hukommelsen";

// translations fr_FR
    QString base_fr_FR = "Sois communicatif|";
            base_fr_FR = base_fr_FR + "Afficher les fichiers dans les archives|";
            base_fr_FR = base_fr_FR + "Activer les messages de débogage de libclamav|";
            base_fr_FR = base_fr_FR + "N'afficher que les messages d'erreur|";
            base_fr_FR = base_fr_FR + "Écrire dans stdout au lieu de stderr. Ne concerne pas les messages 'debug'.|";
            base_fr_FR = base_fr_FR + "Désactiver le résumé de l'analyse à la fin du processus d'analyse|";
            base_fr_FR = base_fr_FR + "N'afficher que les fichiers infectés|";
            base_fr_FR = base_fr_FR + "Saute la sortie des fichiers OK|";
            base_fr_FR = base_fr_FR + "Sonnerie en cas de détection de virus|";
            base_fr_FR = base_fr_FR + "Ne pas supprimer les fichiers temporaires|";
            base_fr_FR = base_fr_FR + "Crée une description JSON des fichiers scannés. Le JSON est produit et aussi-|";
            base_fr_FR = base_fr_FR + "Ne charger que les signatures officielles|";
            base_fr_FR = base_fr_FR + "Scanne les sous-répertoires de manière récursive|";
            base_fr_FR = base_fr_FR + "Poursuivre l'analyse du fichier lorsqu'une réponse positive est obtenue.|";
            base_fr_FR = base_fr_FR + "Analyse des fichiers et des répertoires sur d'autres systèmes de fichiers|";
            base_fr_FR = base_fr_FR + "Supprimer les fichiers infectés. Soyez prudent !|";
            base_fr_FR = base_fr_FR + "Charger un code d'octet non signé|";
            base_fr_FR = base_fr_FR + "Détecte les applications probablement indésirables|";
            base_fr_FR = base_fr_FR + "Reconnaître les données structurées (SSN, carte de crédit)|";
            base_fr_FR = base_fr_FR + "Scanner les fichiers de messagerie|";
            base_fr_FR = base_fr_FR + "Activer la détection du phishing avec les signatures d'e-mail|";
            base_fr_FR = base_fr_FR + "Activer la signature URL et la détection du phishing|";
            base_fr_FR = base_fr_FR + "Alertes heuristiques|";
            base_fr_FR = base_fr_FR + "Arrêtez la recherche dès qu'une correspondance heuristique est trouvée.|";
            base_fr_FR = base_fr_FR + "Normaliser les fichiers HTML, les scripts et les fichiers texte. Utilisez normalize=no pour la compatibilité avec Yara|";
            base_fr_FR = base_fr_FR + "Scanner des fichiers PE|";
            base_fr_FR = base_fr_FR + "Scanner des fichiers ELF|";
            base_fr_FR = base_fr_FR + "Scanner un conteneur OLE2|";
            base_fr_FR = base_fr_FR + "Scanner des fichiers PDF|";
            base_fr_FR = base_fr_FR + "Scanner des fichiers SWF|";
            base_fr_FR = base_fr_FR + "Scanner des fichiers HTML|";
            base_fr_FR = base_fr_FR + "scanner des fichiers de documents basés sur xml|";
            base_fr_FR = base_fr_FR + "Scanner des fichiers HWP3|";
            base_fr_FR = base_fr_FR + "Numérisation de fichiers d'archive (prise en charge par libclamav)|";
            base_fr_FR = base_fr_FR + "Alerte aux fichiers exécutables défectueux (PE & ELF)|";
            base_fr_FR = base_fr_FR + "Avertissement en cas de fichiers graphiques défectueux (JPEG, TIFF, PNG, GIF)|";
            base_fr_FR = base_fr_FR + "Avertissement sur les archives et documents cryptés|";
            base_fr_FR = base_fr_FR + "Avertissement sur les archives cryptées|";
            base_fr_FR = base_fr_FR + "Avertissement pour les documents cryptés|";
            base_fr_FR = base_fr_FR + "Avertissement concernant les fichiers OLE2 contenant des macros VBA|";
            base_fr_FR = base_fr_FR + "Avertissement pour les fichiers dépassant la taille maximale du fichier, la taille maximale de l'analyse ou la limite maximale de récursivité|";
            base_fr_FR = base_fr_FR + "Avertissement pour les e-mails contenant des URL mal adaptées au protocole SSL|";
            base_fr_FR = base_fr_FR + "Avertissement pour les e-mails contenant des URL déguisées|";
            base_fr_FR = base_fr_FR + "Avertissement pour les fichiers image DMG bruts contenant des chevauchements de partitions|";
            base_fr_FR = base_fr_FR + "Désactiver la vérification de la chaîne de certificats Authenticode dans les fichiers PE|";
            base_fr_FR = base_fr_FR + "Dump de la chaîne de certificats Authenticode dans les fichiers PE|";
            base_fr_FR = base_fr_FR + "Désactiver la mise en cache et les contrôles de cache pour les sommes de hachage des fichiers analysés.|";
// new with version 1.4.2 of clamav
            base_fr_FR = base_fr_FR + "Créer des fichiers temporaires pour les analyses de fichiers imbriqués qui, autrement, seraient uniquement en mémoire.|";
            base_fr_FR = base_fr_FR + "Générer des métadonnées JSON pour le(s) fichier(s) numérisé(s). A utiliser UNIQUEMENT pour les tests et le développement.|";
            base_fr_FR = base_fr_FR + "Retourne un code d'erreur non nul si la base de données virale est obsolète.|";
            base_fr_FR = base_fr_FR + "Numériser des fichiers OneNote|";
            base_fr_FR = base_fr_FR + "Numériser des fichiers d'images (graphiques)|";
            base_fr_FR = base_fr_FR + "Détecter les fichiers en calculant les hachages flous des images (graphiques)|";
            base_fr_FR = base_fr_FR + "Créer des fichiers temporaires pour les analyses de fichiers imbriqués qui, autrement, seraient uniquement en mémoire.";

// translations es_ES
    QString base_es_ES = "Sea comunicativo|";
            base_es_ES = base_es_ES + "Visualizar ficheros dentro de archivos|";
            base_es_ES = base_es_ES + "Activar los mensajes de depuración de libclamav|";
            base_es_ES = base_es_ES + "Sólo mensajes de error|";
            base_es_ES = base_es_ES + "Escribe en stdout en lugar de stderr. No afecta a los mensajes de depuración.|";
            base_es_ES = base_es_ES + "Desactivar el resumen de escaneo al final del proceso de escaneo|";
            base_es_ES = base_es_ES + "Sólo archivos infectados|";
            base_es_ES = base_es_ES + "Omitir la salida de archivos OK|";
            base_es_ES = base_es_ES + "Campana para la detección de virus|";
            base_es_ES = base_es_ES + "No eliminar los archivos temporales|";
            base_es_ES = base_es_ES + "Crea una descripción JSON de los archivos escaneados. Se emite JSON y también|";
            base_es_ES = base_es_ES + "Cargar sólo firmas oficiales|";
            base_es_ES = base_es_ES + "Explorar subdirectorios recursivamente|";
            base_es_ES = base_es_ES + "Continuar la búsqueda en el fichero si se obtiene una respuesta positiva|";
            base_es_ES = base_es_ES + "Escanear archivos y directorios en otros sistemas de archivos|";
            base_es_ES = base_es_ES + "Elimine los archivos infectados. ¡Cuidado!|";
            base_es_ES = base_es_ES + "Cargar bytecode no segmentado|";
            base_es_ES = base_es_ES + "Reconocer aplicaciones presuntamente no deseadas|";
            base_es_ES = base_es_ES + "Reconocer datos estructurados (SSN, tarjeta de crédito)|";
            base_es_ES = base_es_ES + "Escanear archivos de correo|";
            base_es_ES = base_es_ES + "Activar la detección de phishing con firmas de correo electrónico|";
            base_es_ES = base_es_ES + "Activar la firma de URL y la detección de phishing|";
            base_es_ES = base_es_ES + "Advertencias heurísticas|";
            base_es_ES = base_es_ES + "Detener la búsqueda en cuanto se encuentre una coincidencia heurística.|";
            base_es_ES = base_es_ES + "Normalice los archivos HTML, script y de texto. Utilice normalise=no para compatibilidad con Yara|";
            base_es_ES = base_es_ES + "Escanear archivos PE|";
            base_es_ES = base_es_ES + "Escanear archivos ELF|";
            base_es_ES = base_es_ES + "Escanear contenedor OLE2|";
            base_es_ES = base_es_ES + "Escanear archivos PDF|";
            base_es_ES = base_es_ES + "Escanear archivos SWF|";
            base_es_ES = base_es_ES + "Escanear archivos HTML|";
            base_es_ES = base_es_ES + "Escanear archivos de documentos basados en xml|";
            base_es_ES = base_es_ES + "Escanear archivos HWP3|";
            base_es_ES = base_es_ES + "Escaneado de archivos comprimidos (compatible con libclamav)|";
            base_es_ES = base_es_ES + "Advertencia de archivos ejecutables defectuosos (PE y ELF)|";
            base_es_ES = base_es_ES + "Advertencia sobre archivos gráficos defectuosos (JPEG, TIFF, PNG, GIF)|";
            base_es_ES = base_es_ES + "Advertencia sobre archivos y documentos cifrados|";
            base_es_ES = base_es_ES + "Advertencia para archivos encriptados|";
            base_es_ES = base_es_ES + "Advertencia sobre documentos encriptados|";
            base_es_ES = base_es_ES + "Advertencia sobre archivos OLE2 que contienen macros VBA|";
            base_es_ES = base_es_ES + "Advertencia para archivos que superen el tamaño máximo de archivo, el tamaño máximo de escaneado o el límite máximo de recursión|";
            base_es_ES = base_es_ES + "Advertencia para los mensajes de correo electrónico que contengan errores SSL en las URL|";
            base_es_ES = base_es_ES + "Advertencia para los correos electrónicos con URL camufladas|";
            base_es_ES = base_es_ES + "Advertencia para archivos de imagen DMG sin procesar que contienen solapamientos de particiones|";
            base_es_ES = base_es_ES + "Desactivación de la comprobación de la cadena de certificados Authenticode en archivos PE|";
            base_es_ES = base_es_ES + "Volcado de la cadena de certificados Authenticode en archivos PE|";
            base_es_ES = base_es_ES + "Desactivar el almacenamiento en caché y las comprobaciones en caché de las sumas hash de los archivos escaneados.|";
// new with version 1.4.2 of clamav
            base_es_ES = base_es_ES + "Crear archivos temporales para exploraciones de archivos anidados que, de otro modo, sólo estarían en memoria.|";
            base_es_ES = base_es_ES + "Generar metadatos JSON para los archivos escaneados. SÓLO para pruebas y desarrollo.|";
            base_es_ES = base_es_ES + "Devuelve un código de error distinto de cero si la base de datos de virus no está actualizada.|";
            base_es_ES = base_es_ES + "Escanear archivos de OneNote|";
            base_es_ES = base_es_ES + "Escanear archivos de imagen (gráficos)|";
            base_es_ES = base_es_ES + "Detección de archivos mediante el cálculo de hashes difusos de imágenes (gráficos)|";
            base_es_ES = base_es_ES + "Crear archivos temporales para exploraciones de archivos anidados que, de otro modo, sólo estarían en memoria.";

// translation uk_UA
    QString base_uk_UA = "Будьте багатослівні|";
            base_uk_UA = base_uk_UA + "Показувати імена файлів всередині відсканованих архівів|";
            base_uk_UA = base_uk_UA + "Увімкнути налагоджувальні повідомлення libclamav|";
            base_uk_UA = base_uk_UA + "Виводити тільки повідомлення про помилки|";
            base_uk_UA = base_uk_UA + "Писати до stdout замість stderr. Не впливає на «налагоджувальні» повідомлення.|";
            base_uk_UA = base_uk_UA + "Вимкнути підсумок в кінці сканування|";
            base_uk_UA = base_uk_UA + "Друкуйте лише заражені файли|";
            base_uk_UA = base_uk_UA + "Пропустити друк файлів OK|";
            base_uk_UA = base_uk_UA + "Звуковий сигнал при виявленні вірусу|";
            base_uk_UA = base_uk_UA + "Не видаляйте тимчасові файли|";
            base_uk_UA = base_uk_UA + "Згенеруйте JSON опис відсканованого файлу(ів). JSON буде надруковано, а також|";
            base_uk_UA = base_uk_UA + "Завантажуйте лише офіційні підписи|";
            base_uk_UA = base_uk_UA + "Сканувати підкаталоги рекурсивно|";
            base_uk_UA = base_uk_UA + "Після знаходження збігу продовжити сканування у файлі|";
            base_uk_UA = base_uk_UA + "Сканування файлів і каталогів в інших файлових системах|";
            base_uk_UA = base_uk_UA + "Видаліть заражені файли. Обережно!|";
            base_uk_UA = base_uk_UA + "Завантажити беззнаковий байт-код|";
            base_uk_UA = base_uk_UA + "Виявлення можливих небажаних програм|";
            base_uk_UA = base_uk_UA + "Виявлення структурованих даних (SSN, кредитна картка)|";
            base_uk_UA = base_uk_UA + "Сканувати поштові файли|";
            base_uk_UA = base_uk_UA + "Увімкнути виявлення фішингу за підписом електронної пошти|";
            base_uk_UA = base_uk_UA + "Увімкнути виявлення фішингу на основі сигнатур URL-адрес|";
            base_uk_UA = base_uk_UA + "Евристичні сповіщення|";
            base_uk_UA = base_uk_UA + "Зупиніть сканування, як тільки буде знайдено евристичний збіг|";
            base_uk_UA = base_uk_UA + "Нормалізувати html, скриптові та текстові файли. Використовуйте normalize=no для сумісності з yara|";
            base_uk_UA = base_uk_UA + "Сканувати PE-файли|";
            base_uk_UA = base_uk_UA + "Сканувати ELF-файли|";
            base_uk_UA = base_uk_UA + "Сканування контейнерів OLE2|";
            base_uk_UA = base_uk_UA + "Сканувати PDF-файли|";
            base_uk_UA = base_uk_UA + "Сканувати SWF-файли|";
            base_uk_UA = base_uk_UA + "Сканування HTML-файлів|";
            base_uk_UA = base_uk_UA + "Сканування файлів документів у форматі xml|";
            base_uk_UA = base_uk_UA + "Сканувати файли HWP3|";
            base_uk_UA = base_uk_UA + "Сканування архівних файлів (підтримується libclamav)|";
            base_uk_UA = base_uk_UA + "Сповіщення про пошкоджені виконувані файли (PE та ELF)|";
            base_uk_UA = base_uk_UA + "Сповіщення про пошкоджені графічні файли (JPEG, TIFF, PNG, GIF)|";
            base_uk_UA = base_uk_UA + "Сповіщення про зашифровані архіви та документи|";
            base_uk_UA = base_uk_UA + "Сповіщення про зашифровані архіви|";
            base_uk_UA = base_uk_UA + "Сповіщення про зашифровані документи|";
            base_uk_UA = base_uk_UA + "Попередження про OLE2-файли, що містять макроси VBA|";
            base_uk_UA = base_uk_UA + "Сповіщення про файли, які перевищують максимальний розмір файлу, максимальний розмір сканування або максимальний ліміт рекурсії|";
            base_uk_UA = base_uk_UA + "Сповіщення про імейли, що містять SSL невідповідності в URL-адресах|";
            base_uk_UA = base_uk_UA + "Сповіщення про листи, що містять приховані URL-адреси|";
            base_uk_UA = base_uk_UA + "Сповіщення про необроблені файли зображень DMG, що містять перетини розділів|";
            base_uk_UA = base_uk_UA + "Вимкнути перевірку ланцюжка сертифікатів автентичності в PE-файлах|";
            base_uk_UA = base_uk_UA + "Дамп ланцюжка сертифікатів authenticode у PE-файлах|";
            base_uk_UA = base_uk_UA + "Вимкнути кешування та перевірку хеш-сум сканованих файлів.|";
// new with version 1.4.2 of clamav
            base_uk_UA = base_uk_UA + "Створюйте тимчасові файли для сканування вкладених файлів, які інакше були б тільки в пам'яті|";
            base_uk_UA = base_uk_UA + "Згенеруйте метадані JSON для відсканованого файлу(ів). Використовувати ТІЛЬКИ для тестування та розробки.|";
            base_uk_UA = base_uk_UA + "Повертається ненульовий код помилки, якщо вірусна база даних застаріла.|";
            base_uk_UA = base_uk_UA + "Сканування файлів OneNote|";
            base_uk_UA = base_uk_UA + "Сканувати файли зображень (графіки)|";
            base_uk_UA = base_uk_UA + "Виявлення файлів шляхом обчислення нечітких хешів зображень (графіки)|";
            base_uk_UA = base_uk_UA + "Створюйте тимчасові файли для сканування вкладених файлів, які інакше були б тільки в пам'яті";

// End of DATA-Block

    QStringList originals = base.split("|");
    QStringList translations;
    QString rc = original;

    if (languageset == "[de_DE]") translations = base_de_DE.split("|");
    if ((languageset == "[pt_PT]") || (languageset == "[pt_AO]") || (languageset == "[pt_BR]") || (languageset == "[pt_CV]") || (languageset == "[pt_MZ]") || (languageset == "[pt_MO]") || (languageset == "[pt_ST]") || (languageset == "[pt_TL]")) translations = base_pt_PT.split("|");
    if (languageset == "[it_IT]") translations = base_it_IT.split("|");
    if (languageset == "[da_DK]") translations = base_da_DK.split("|");
    if (languageset == "[fr_FR]") translations = base_fr_FR.split("|");
    if (languageset == "[es_ES]") translations = base_es_ES.split("|");
    if (languageset == "[uk_UA]") translations = base_uk_UA.split("|");
    if (translations.length() == 0) translations = base.split("|");

    QString helper;
    int counter = 0;
    int pos = originals.indexOf(original);

    if (pos != -1) {
        rc = "";
        helper = translations.at(pos);
    }

    for (int i = 0; i < helper.length(); i++) {
        if ((counter > 60) && (helper.mid(i,1) == ' ')) {
            rc = rc + "\n";
            counter = 0;
        } else {
            rc = rc + helper.mid(i,1);
        }
        counter++;
    }
    return rc;
}
